# Within web we set build to look in the current directory for our Dockerfile. We’ll use the Django
# default ports of 8000 and execute the command to run the local web server. Finally the volumes24
# mount automatically syncs the Docker filesystem with our local computer’s filesystem. This if we
# make a change to the code within Docker it will automatically be synced with the local filesystem

version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:


